language: cpp

compiler:
  - clang
notifications:
  email: false
env:
  global:
    - R_LIBS_USER=~/R
  matrix: 
    # - JULIAVERSION="juliareleases" Require Julia 0.3 or greater.
    - JULIAVERSION="julianightlies" 
before_install:
  # Install Julia
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  # Install Python scikit-learn
  - sudo apt-get build-dep python-sklearn -y
  - sudo pip install -U scikit-learn
  # Install R
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update -qq -y
  - sudo apt-get install r-base-dev r-recommended
  - "[ ! -d ${R_LIBS_USER} ] && mkdir ${R_LIBS_USER}"
  # Install R Caret
  - Rscript -e 'install.packages("caret", dependencies = c("Depends", "Suggests"))'
  # Install RPy2
  - sudo pip install rpy2
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Orchestra"))`); Pkg.pin("Orchestra"); Pkg.resolve()'
  - julia -e 'using Orchestra; @assert isdefined(:Orchestra); @assert typeof(Orchestra) === Module'
  - julia test/runner.jl
  - julia test/test_system.jl
